baseURL = 'https://tdi.github.io'
languageCode = 'en-us'
title = "Darek's Blog"
theme = 'PaperMod'

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Darek's Blog"
description = "Documenting my thoughts"
keywords = ["Blog", "Portfolio", "CTO", "Blockchain", "Web3", "Crypto"]
author = "Darek Dwornikowski"
# author = ["Me", "You"] # multiple authors
images = ["/static/openg.png"]
DateFormat = "January 2, 2006"
defaultTheme = "auto"          # dark, light
disableThemeToggle = false

ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

[params.assets]
# disableHLJS = true # to disable highlight.js
# disableFingerprinting = true
favicon = "<link / abs url>"
favicon16x16 = "<link / abs url>"
favicon32x32 = "<link / abs url>"
apple_touch_icon = "<link / abs url>"
safari_pinned_tab = "<link / abs url>"

[params.label]
text = "Darek's Blog"
icon = "/apple-touch-icon.png"
iconHeight = 35

# profile-mode
[params.profileMode]
enabled = false                                                                  # needs to be explicitly set
title = "CTO Learning Blockchain"
subtitle = "20+ years in tech, now diving into Web3"
imageUrl = "<title / alt>"
imageWidth = 120
imageHeight = 120
imageTitle = "ProfileMode image"
buttons = [{ name = "Posts", url = "/posts" }, { name = "Tags", url = "/tags" }]

# home-info mode
[params.homeInfoParams]
Title = "Hi there 👋"
Content = "Welcome to my blog documenting my journey from traditional CTO to Web3. I'm sharing everything I learn about blockchain, smart contracts, and crypto as I make this mild career transition."

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/darek_dwo"

[[params.socialIcons]]
name = "github"
url = "https://github.com/tdi"

[[params.socialIcons]]
name = "linkedin"
url = "https://linkedin.com/in/darekd"

[params.analytics.google]
SiteVerificationTag = "XYZabc"

[params.cover]
hidden = true         # hide everywhere but not in structured data
hiddenInList = true   # hide on list pages and home
hiddenInSingle = true # hide on single page

[params.editPost]
URL = "https://github.com/tdi/tdi.github.io/tree/main/content"
Text = "Suggest Changes"                                       # edit text
appendFilePath = true                                          # to append file path to Edit link

# for search
# https://fusejs.io/api/options.html
[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1000
threshold = 0.4
minMatchCharLength = 0
keys = ["title", "permalink", "summary", "content"]

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10


[[menu.main]]
identifier = "categories"
name = "categories"
url = "/categories/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 20

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses = true
[markup]
[markup.highlight]
noClasses = false
# anchorLineNos = true
# codeFences = true
# guessSyntax = true
# lineNos = true
# style = "github"
[caches]
[caches.images]
dir = ':cacheDir/images'
